const sequelize = require("../bin/dbConnection");
const users = require("./definitions/users");
const buses = require("./definitions/buses");
const routes = require("./definitions/routes");
const models = { users, buses, routes };
const db = {};
db.sequelize = sequelize;
sequelize.models = models;
module.exports = { db, models };
