const sequelize = require("../bin/dbConnection");
const users = require("./definitions/users");
const buses = require("./definitions/buses");
const routes = require("./definitions/routes");
const trips = require("./definitions/trips");
const models = { users, buses, routes, trips };
buses.hasMany(trips, { foreignKey: "busId" });
trips.belongsTo(buses, { foreignKey: "busId" });
routes.hasMany(trips, { foreignKey: "routeId" });
trips.belongsTo(routes, { foreignKey: "routeId" });
const db = {};
db.sequelize = sequelize;
sequelize.models = models;
module.exports = { db, models };
