const sequelize = require("../bin/dbConnection");
const users = require("./definitions/users");
const buses = require("./definitions/buses");
const routes = require("./definitions/routes");
const trips = require("./definitions/trips");
const bookings = require("./definitions/bookings");
const sessions = require("./definitions/session");
const models = { users, buses, routes, trips, bookings, sessions };
buses.hasMany(trips, { foreignKey: "busId" });
trips.belongsTo(buses, { foreignKey: "busId" });
routes.hasMany(trips, { foreignKey: "routeId" });
trips.belongsTo(routes, { foreignKey: "routeId" });
users.hasMany(bookings, { foreignKey: "userId" });
bookings.belongsTo(users, { foreignKey: "userId" });
trips.hasMany(bookings, { foreignKey: "tripId" });
bookings.belongsTo(trips, { foreignKey: "tripId" });
users.hasOne(sessions, { foreignKey: "userId" });
sessions.belongsTo(users, { foreignKey: "userId" });
const db = {};
db.sequelize = sequelize;
sequelize.models = models;
module.exports = { db, models };
